# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  push: {}
  # Allows you to run this workflow manually from the Actions tab Here is the branch change

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  autoupdate:
    name: autoupdate
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: brainly/action-autoupdate-branch@2.1.1
        id: autoupdate
        env:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
