# This is a basic workflow to help you get started with Actions
name: Auto Update

# Controls when the action will run. 
on: [push]
  # Allows you to run this workflow manually from the Actions tab testing edited here

# A workflow run is made up of one or more jobs that can run sequentially or in parallel testing edited
jobs:
  autoupdate:
    name: autoupdate
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: adRise/update-pr-branch@v0.6.0
        id: autoupdate
        with:
          token: ${{ secrets.ACTION_USER_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: false
